<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Avatar Default',
                'short_description' => NULL,
                'description' => NULL,
                'image' => 'https://welore.io/images/profile/profile-1.jpg',
                'video_purchase' => NULL,
                'price_fiat' => 0.0,
                'price_oro' => 0,
                'price_plumas' => 10,
                'active' => 0,
                'product_parent_id' => NULL,
                'oro' => 0,
                'plumas' => 0,
                'nft_id' => 1,
                'rarity' => NULL,
                'tags' => NULL,
                'nft_serial_greater_equal' => NULL,
                'nft_serial_less_equal' => NULL,
                'custom' => NULL,
                'one_time_purchase' => 0,
                'one_time_purchase_global' => 0,
                'order' => NULL,
                'created_at' => '2025-07-01 20:02:50',
                'updated_at' => '2025-07-01 20:05:23',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Puñado de diamantes x10',
                'short_description' => NULL,
                'description' => NULL,
                'image' => 'https://reports.madfenix.com/welore/demo-assets/store/punado_diamantes_web.png',
                'video_purchase' => NULL,
                'price_fiat' => 5.0,
                'price_oro' => 0,
                'price_plumas' => 0,
                'active' => 1,
                'product_parent_id' => NULL,
                'oro' => 10,
                'plumas' => 0,
                'nft_id' => NULL,
                'rarity' => NULL,
                'tags' => NULL,
                'nft_serial_greater_equal' => NULL,
                'nft_serial_less_equal' => NULL,
                'custom' => NULL,
                'one_time_purchase' => 0,
                'one_time_purchase_global' => 0,
                'order' => '1010',
                'created_at' => '2025-07-07 16:08:30',
                'updated_at' => '2025-07-07 16:17:41',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Maletín de diamantes x43',
                'short_description' => NULL,
                'description' => NULL,
                'image' => 'https://reports.madfenix.com/welore/demo-assets/store/maletin_diamantes_web.png',
                'video_purchase' => NULL,
                'price_fiat' => 20.0,
                'price_oro' => 0,
                'price_plumas' => 0,
                'active' => 1,
                'product_parent_id' => NULL,
                'oro' => 43,
                'plumas' => 0,
                'nft_id' => NULL,
                'rarity' => NULL,
                'tags' => NULL,
                'nft_serial_greater_equal' => NULL,
                'nft_serial_less_equal' => NULL,
                'custom' => NULL,
                'one_time_purchase' => 0,
                'one_time_purchase_global' => 0,
                'order' => '1030',
                'created_at' => '2025-07-07 16:18:24',
                'updated_at' => '2025-07-07 16:19:34',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Estuche de diamantes x21',
                'short_description' => NULL,
                'description' => NULL,
                'image' => 'https://reports.madfenix.com/welore/demo-assets/store/estuche_diamantes_web.png',
                'video_purchase' => NULL,
                'price_fiat' => 10.0,
                'price_oro' => 0,
                'price_plumas' => 0,
                'active' => 1,
                'product_parent_id' => NULL,
                'oro' => 21,
                'plumas' => 0,
                'nft_id' => NULL,
                'rarity' => NULL,
                'tags' => NULL,
                'nft_serial_greater_equal' => NULL,
                'nft_serial_less_equal' => NULL,
                'custom' => NULL,
                'one_time_purchase' => 0,
                'one_time_purchase_global' => 0,
                'order' => '1020',
                'created_at' => '2025-07-07 16:19:27',
                'updated_at' => '2025-07-07 16:19:27',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Cofre de diamantes x90',
                'short_description' => NULL,
                'description' => NULL,
                'image' => 'https://reports.madfenix.com/welore/demo-assets/store/cofre_diamantes_web.png',
                'video_purchase' => NULL,
                'price_fiat' => 40.0,
                'price_oro' => 0,
                'price_plumas' => 0,
                'active' => 1,
                'product_parent_id' => NULL,
                'oro' => 90,
                'plumas' => 0,
                'nft_id' => NULL,
                'rarity' => NULL,
                'tags' => NULL,
                'nft_serial_greater_equal' => NULL,
                'nft_serial_less_equal' => NULL,
                'custom' => NULL,
                'one_time_purchase' => 0,
                'one_time_purchase_global' => 0,
                'order' => '1040',
                'created_at' => '2025-07-07 16:20:36',
                'updated_at' => '2025-07-07 16:20:36',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Cinta de diamantes x190',
                'short_description' => NULL,
                'description' => NULL,
                'image' => 'https://reports.madfenix.com/welore/demo-assets/store/cinta_diamantes_web.png',
                'video_purchase' => NULL,
                'price_fiat' => 80.0,
                'price_oro' => 0,
                'price_plumas' => 0,
                'active' => 1,
                'product_parent_id' => NULL,
                'oro' => 180,
                'plumas' => 0,
                'nft_id' => NULL,
                'rarity' => NULL,
                'tags' => NULL,
                'nft_serial_greater_equal' => NULL,
                'nft_serial_less_equal' => NULL,
                'custom' => NULL,
                'one_time_purchase' => 0,
                'one_time_purchase_global' => 0,
                'order' => '1050',
                'created_at' => '2025-07-07 16:21:29',
                'updated_at' => '2025-07-07 16:21:29',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Megadrop de diamantes x400',
                'short_description' => NULL,
                'description' => NULL,
                'image' => 'https://reports.madfenix.com/welore/demo-assets/store/megadrop_diamantes_web.png',
                'video_purchase' => NULL,
                'price_fiat' => 160.0,
                'price_oro' => 0,
                'price_plumas' => 0,
                'active' => 1,
                'product_parent_id' => NULL,
                'oro' => 400,
                'plumas' => 0,
                'nft_id' => NULL,
                'rarity' => NULL,
                'tags' => NULL,
                'nft_serial_greater_equal' => NULL,
                'nft_serial_less_equal' => NULL,
                'custom' => NULL,
                'one_time_purchase' => 0,
                'one_time_purchase_global' => 0,
                'order' => '1060',
                'created_at' => '2025-07-07 16:22:19',
                'updated_at' => '2025-07-07 16:22:19',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Rewards Pass VIP',
                'short_description' => NULL,
                'description' => NULL,
                'image' => 'https://reports.madfenix.com/welore/demo-assets/store/pase_vip_web.png',
                'video_purchase' => NULL,
                'price_fiat' => 0.0,
                'price_oro' => 20,
                'price_plumas' => 0,
                'active' => 1,
                'product_parent_id' => NULL,
                'oro' => 0,
                'plumas' => 0,
                'nft_id' => NULL,
                'rarity' => NULL,
                'tags' => NULL,
                'nft_serial_greater_equal' => NULL,
                'nft_serial_less_equal' => NULL,
                'custom' => 'Pase de temporada premium',
                'one_time_purchase' => 0,
                'one_time_purchase_global' => 0,
                'order' => '1070',
                'created_at' => '2025-07-07 16:24:22',
                'updated_at' => '2025-07-07 16:24:22',
            ),
        ));
        
        
    }
}